import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@canny_ecosystem/ui/sheet";
import { cn } from "@canny_ecosystem/ui/utils/cn";
import { useState, useEffect, useMemo } from "react";
import { Combobox } from "@canny_ecosystem/ui/combobox";
import { Label } from "@canny_ecosystem/ui/label";
import { Input } from "@canny_ecosystem/ui/input";
import { Button } from "@canny_ecosystem/ui/button";
import { useSubmit, useLocation } from "@remix-run/react";
import { Icon } from "@canny_ecosystem/ui/icon";

export function DivideFieldsSheet({
  payrollId,
  selectedRows,
  uniqueFields,
  triggerChild,
}: {
  payrollId: string;
  selectedRows: any[];
  uniqueFields: { name: string; type: "earning" | "deduction"; id?: string }[];
  triggerChild: React.ReactNode;
}) {
  const [open, setOpen] = useState<boolean>(false);
  const submit = useSubmit();
  const location = useLocation();

  // Filter selected rows to only include manually entered/persisted rows (skip autogenerated)
  // Memoized to keep a stable reference and prevent useEffect infinite loops
  const eligibleRows = useMemo(
    () => selectedRows.filter((row) => row.source !== "auto"),
    [selectedRows],
  );

  const [sourceFieldName, setSourceFieldName] = useState("");
  const [targetFieldName, setTargetFieldName] = useState("");
  const [amount, setAmount] = useState<number>(0);
  const [percentage, setPercentage] = useState<number>(0);
  const [shares, setShares] = useState<Record<string, number>>({});

  // Helper to extract current value of source field for a row
  const getSourceFieldValue = (row: any, fieldName: string) => {
    if (!fieldName) return 0;
    const valObj = row.salary_entries?.salary_field_values?.find(
      (entry: any) =>
        entry.payroll_fields?.name?.trim().toLowerCase() ===
        fieldName.trim().toLowerCase(),
    );
    return Number(valObj?.amount ?? 0);
  };

  // Find source field definition
  const sourceFieldDef = uniqueFields.find(
    (f) => f.name.toLowerCase() === sourceFieldName.toLowerCase(),
  );
  const sourceFieldType = sourceFieldDef?.type ?? "earning";
  const sourceFieldId = sourceFieldDef?.id ?? "";

  // Filter target fields by type of source field (and exclude source itself)
  const targetFieldOptions = uniqueFields
    .filter(
      (f) =>
        f.type === sourceFieldType &&
        f.name.toLowerCase() !== sourceFieldName.toLowerCase(),
    )
    .map((f) => ({
      label: f.name,
      value: f.name,
    }));

  // Recalculate shares when amount, percentage, source field, or eligible rows change
  useEffect(() => {
    const newShares: Record<string, number> = {};
    if (eligibleRows.length === 0) return;

    eligibleRows.forEach((row) => {
      const currentSourceVal = getSourceFieldValue(row, sourceFieldName);
      const targetVal = Math.min(
        percentage > 0
          ? Math.round(currentSourceVal * (percentage / 100) * 100) / 100
          : amount,
        currentSourceVal,
      );
      newShares[row.id] = targetVal;
    });
    setShares(newShares);
  }, [amount, percentage, sourceFieldName, selectedRows]);

  const handleAmountChange = (val: number) => {
    setAmount(val);
    setPercentage(0);
  };

  const handlePercentageChange = (val: number) => {
    setPercentage(val);
    setAmount(0);
  };

  const handleShareChange = (rowId: string, value: number) => {
    setShares((prev) => ({
      ...prev,
      [rowId]: value,
    }));
  };

  const handleFinalSubmit = () => {
    const distributions = eligibleRows.map((row) => {
      const currentSourceVal = getSourceFieldValue(row, sourceFieldName);
      const targetVal = shares[row.id] ?? 0;
      const newSourceVal = Math.max(0, currentSourceVal - targetVal);

      return {
        monthly_attendance_id: row.id,
        salary_entry_id: row.salary_entries?.id,
        sourceAmount: newSourceVal,
        targetAmount: targetVal,
      };
    });

    submit(
      {
        sourceFieldId,
        sourceFieldName,
        targetFieldName,
        fieldType: sourceFieldType,
        distributions: JSON.stringify(distributions),
      },
      {
        method: "POST",
        action: `/payroll/run-payroll/${payrollId}/divide-fields${location.search}`,
      },
    );
    setOpen(false);
  };

  const totalTargetDistributed = Object.values(shares).reduce(
    (sum, val) => sum + val,
    0,
  );

  const sourceFieldOptions = uniqueFields.map((f) => ({
    label: `${f.name} (${f.type === "earning" ? "Earning" : "Deduction"})`,
    value: f.name,
  }));

  return (
    <Sheet open={open} onOpenChange={setOpen}>
      <SheetTrigger
        asChild
        className={cn("cursor-pointer py-2 w-full text-left")}
      >
        {triggerChild}
      </SheetTrigger>
      <SheetContent className="flex flex-col w-[600px] max-sm:w-full h-full max-h-screen">
        <SheetHeader className="px-6 pt-4 pb-4 flex-shrink-0">
          <SheetTitle className="flex justify-between">
            <div>
              <h1 className="text-primary text-3xl">Separate Fields</h1>
            </div>
          </SheetTitle>
        </SheetHeader>
        <div className="flex-1 overflow-y-auto px-6 pb-4 space-y-6">
          <div className="flex items-start gap-3 bg-blue-50/50 dark:bg-blue-950/10 border border-blue-200 dark:border-blue-900/50 p-4 rounded-lg text-sm text-blue-800 dark:text-blue-400">
            <Icon
              name="info"
              className="h-5 w-5 mt-0.5 flex-shrink-0 text-blue-500"
            />
            <div>
              Select a source field to separate from, and type or choose a
              target field to move values into. Only selected employees with
              saved/modified values are eligible. Autogenerated rows are
              skipped.
            </div>
          </div>

          {eligibleRows.length === 0 && (
            <div className="flex items-start gap-3 bg-amber-50/50 dark:bg-amber-950/10 border border-amber-200 dark:border-amber-900/50 p-4 rounded-lg text-sm text-amber-800 dark:text-amber-400">
              <Icon
                name="info"
                className="h-5 w-5 mt-0.5 flex-shrink-0 text-amber-500"
              />
              <div>
                No eligible employees selected. Autogenerated rows cannot be
                separated until they have been saved/modified once.
              </div>
            </div>
          )}

          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1.5">
              <Label className="text-sm font-medium">
                Source Field (Separate From)
              </Label>
              <Combobox
                options={sourceFieldOptions}
                placeholder="Select source field"
                value={sourceFieldName}
                onChange={(value: string) => {
                  setSourceFieldName(value);
                  setTargetFieldName(""); // Reset target when source changes
                }}
                disabled={eligibleRows.length === 0}
              />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label className="text-sm font-medium">
                Target Field (Move Into)
              </Label>
              <Input
                placeholder="Type new or select below"
                value={targetFieldName}
                onChange={(e) => setTargetFieldName(e.target.value)}
                disabled={!sourceFieldName || eligibleRows.length === 0}
              />
              {sourceFieldName && targetFieldOptions.length > 0 && (
                <div className="flex flex-wrap gap-1.5 mt-1 items-center">
                  <span className="text-xs text-muted-foreground">
                    Select existing:
                  </span>
                  {targetFieldOptions.map((opt) => (
                    <button
                      key={opt.value}
                      type="button"
                      onClick={() => setTargetFieldName(String(opt.value))}
                      className={cn(
                        "text-xs px-2 py-0.5 rounded border transition-colors",
                        targetFieldName.toLowerCase() ===
                          String(opt.value).toLowerCase()
                          ? "bg-primary text-primary-foreground border-primary"
                          : "bg-muted text-muted-foreground border-transparent hover:bg-muted/80",
                      )}
                    >
                      {opt.label}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1.5">
              <Label className="text-sm font-medium">Amount to Separate</Label>
              <Input
                type="number"
                placeholder="Enter flat amount"
                value={amount || ""}
                onChange={(e) => handleAmountChange(Number(e.target.value))}
                disabled={
                  percentage > 0 ||
                  !sourceFieldName ||
                  eligibleRows.length === 0
                }
              />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label className="text-sm font-medium">Percentage (%)</Label>
              <Input
                type="number"
                placeholder="Enter % of source value"
                value={percentage || ""}
                onChange={(e) => handlePercentageChange(Number(e.target.value))}
                disabled={
                  amount > 0 || !sourceFieldName || eligibleRows.length === 0
                }
              />
            </div>
          </div>

          <div className="space-y-3">
            <Label className="text-sm font-semibold">
              Distribution Preview ({eligibleRows.length} Eligible)
            </Label>
            <div className="border rounded-md overflow-hidden max-h-60 overflow-y-auto">
              <table className="w-full text-sm">
                <thead className="bg-muted text-muted-foreground sticky top-0">
                  <tr>
                    <th className="px-4 py-2 text-left font-medium text-xs">
                      Employee
                    </th>
                    <th className="px-4 py-2 text-right font-medium text-xs w-24">
                      Current Source
                    </th>
                    <th className="px-4 py-2 text-right font-medium text-xs w-24">
                      New Source
                    </th>
                    <th className="px-4 py-2 text-right font-medium text-xs w-28">
                      Separated Target
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {eligibleRows.map((row) => {
                    const currentSourceVal = getSourceFieldValue(
                      row,
                      sourceFieldName,
                    );
                    const targetVal = shares[row.id] ?? 0;
                    const newSourceVal = Math.max(
                      0,
                      currentSourceVal - targetVal,
                    );
                    return (
                      <tr key={row.id}>
                        <td className="px-4 py-2">
                          <p className="font-medium text-foreground">
                            {row.employee?.first_name} {row.employee?.last_name}
                          </p>
                          <p className="text-xs text-muted-foreground">
                            {row.employee?.employee_code}
                          </p>
                        </td>
                        <td className="px-4 py-2 text-right font-semibold text-muted-foreground">
                          ₹{currentSourceVal.toLocaleString()}
                        </td>
                        <td className="px-4 py-2 text-right font-semibold text-blue-600">
                          ₹{newSourceVal.toLocaleString()}
                        </td>
                        <td className="px-4 py-2 text-right">
                          <Input
                            type="number"
                            className="h-8 text-right pr-2 text-sm w-24 inline-block"
                            value={shares[row.id] ?? 0}
                            onChange={(e) =>
                              handleShareChange(row.id, Number(e.target.value))
                            }
                            max={currentSourceVal}
                            disabled={!sourceFieldName}
                          />
                        </td>
                      </tr>
                    );
                  })}
                  {eligibleRows.length === 0 && (
                    <tr>
                      <td
                        colSpan={4}
                        className="px-4 py-8 text-center text-muted-foreground text-sm"
                      >
                        No eligible employees selected.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          <div className="flex justify-between items-center text-sm border-t pt-4">
            <span className="text-muted-foreground">
              Total Separated Value:
            </span>
            <div className="text-right">
              <span className="font-bold text-base text-green-600">
                ₹
                {totalTargetDistributed.toLocaleString(undefined, {
                  minimumFractionDigits: 2,
                })}
              </span>
              {sourceFieldName && (
                <span className="text-muted-foreground text-xs block">
                  Moving from {sourceFieldName} (
                  {sourceFieldType === "earning" ? "Earning" : "Deduction"}) to{" "}
                  {targetFieldName || "Target Field"}
                </span>
              )}
            </div>
          </div>
        </div>
        <SheetFooter className="px-6 py-4 border-t mt-auto flex-shrink-0">
          <SheetClose asChild>
            <Button
              variant="default"
              onClick={handleFinalSubmit}
              disabled={
                !sourceFieldName ||
                !targetFieldName ||
                totalTargetDistributed <= 0 ||
                eligibleRows.length === 0
              }
              className="w-full"
            >
              Apply Separation
            </Button>
          </SheetClose>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}
